name: "Periodic analysis"

on:
  schedule:
    # Change this in your project to a random time.
    # Every monday at 15:54 UTC
    - cron: "54 15 * * 1"

jobs:
  codeql:
    name: "🔍 Perform CodeQL analysis"
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: "⬇️ Checkout repository"
        uses: actions/checkout@v3

      - name: "🔨 Initialize CodeQL"
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: "🔍 Perform CodeQL analysis"
        uses: github/codeql-action/analyze@v2
